# -*- coding: utf-8 -*-
"""Assignement-3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JY4IlJEBKVP_7P10dI2MoCZsBjlmTCGE
"""

import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
import matplotlib.pyplot as plt

studyData = pd.read_csv('study_score.csv')
# print(studyData)

X = studyData['Hours'].values
X = X.reshape(-1, 1)

y = studyData['Scores'].values
# y = y.reshape(-1,1)


plt.scatter(X, y)

model = LinearRegression()
model.fit(X, y)

line = model.coef_ * X + model.intercept_
plt.plot(X, line, 'black')
plt.scatter(X, y)
plt.title("students' scores")
plt.xlabel("Hour")
plt.ylabel("Score")

predict_value = model.predict([[9]])
print(predict_value[0])
